---
- name: Install oVirt Engine package
  package:
    name: "ovirt-engine"
    state: present
  when: ovirt_engine_setup_product_type | lower == 'ovirt'

- name: Install RHV package
  package:
    name: "{{ 'rhevm' if ovirt_engine_setup_version is version('4.2', '<') else 'rhvm' }}"
    state: present
  when: ovirt_engine_setup_product_type | lower == 'rhv'

- name: Install rest of the packages required for oVirt Engine deployment
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ovirt_engine_setup_package_list }}"
